### ISSUE TITLE
 Spark on Angel seems to only supports vectors, not matrices.

### ISSUE THREAD

**Issue by witgo** [Tencent/angel#10]
If Spark on Angel does not support matrix now, is there a plan to support the matrix?

**Comment by ZunwenYou** [comment]
You are right, Spark on Angel can not support matrix right now. 
We will work on it.

**Comment by Chris19920210** [comment]
Have you ever resolved this problem now?

**Comment by andyyehoo** [comment]
It will be provided in next release version.

**Comment by Chris19920210** [comment]
btw, what about the F+LDA? is it implemented by Spark on Angel? if that's true, how to handle the word-topic table, if you only have the PSVector.

**Comment by ZunwenYou** [comment]
LDA has implement with Angel API. 
Spark on Angel does not have LDA right now, we are working on PSMatrix in Spark-on-Angel.

**Comment by Chris19920210** [comment]
Thx, No offense. What's your schedule？I'm working on a project which involves matrix update. Hence, it will be greatly appreciated if the PSMatrix comimg soon.

**Comment by ZunwenYou** [comment]
That is OK. I will push PSMatrix to latest branch on next Wednesday.

**Comment by Chris19920210** [comment]
Thx, have a nice day!

**Comment by ZunwenYou** [comment]
@Chris19920210 PSMatrix implement have syn to github `branch-1.2.0` on this Wednesday.
