### ISSUE TITLE
销毁PSModelPoool 方法的疑问？

### ISSUE THREAD

**Issue by liamlee** [Tencent/angel#110]
在spark_on_angel_programing_guide.md中提到的

销毁PSModelPoool 使用：context.destroyModelPool(pool)

但实际测试中没有该方法，PSContext中只有destroyVectorPool()

![image](https://user-images.githubusercontent.com/781297/27619753-5775adc6-5bf7-11e7-93fb-faa8a9f76fd1.png)

**Comment by ZunwenYou** [comment]
It is a typo chaos after a few of name refactor. 
This method is `destroyModelPool` in PSContext, I will fix it.
