### ISSUE TITLE
I've just run angel example on local without any problem ,but when come to yarn model , it counter some problem as below,

### ISSUE THREAD

**Issue by yipeng5** [Tencent/angel#122]
someone can tell me why?
my env : 
hadoop
![image](https://user-images.githubusercontent.com/20752672/27820067-9290e65a-60cf-11e7-86c3-7d29984441a0.png)
java
![image](https://user-images.githubusercontent.com/20752672/27820083-aab61de0-60cf-11e7-954d-7113abced04e.png)

![image](https://user-images.githubusercontent.com/20752672/27820097-bb76de44-60cf-11e7-90df-1d9427bc6646.png)

**Comment by lszChain** [comment]
@yipeng5 请问怎么解决的，我也遇到了同样的问题

**Comment by lszChain** [comment]
@yipeng5 How did you solve it? I had the same problem.
