### ISSUE TITLE
when  comes  to predict model ,   it have no indicators on lr algorithm 

### ISSUE THREAD

**Issue by yipeng5** [Tencent/angel#123]

**Comment by yipeng5** [comment]
???

**Comment by TAAAN** [comment]
Thanks for your issue. I have added it to branch-1.0.0/docs/algo/lr_on_angel.md. 
Before you check  it, maybe you can try it yourself,  in this way. 
1. set the action.type: predict or train? 2. denote the runner class, which runner？ 3. what is the in\out path, and model path?  4. resource parameters of workers and PS, number and memmory, even more high level paramaters. 5. other parameters you need in your task, for example learn rate when you train a model. 
If you write your own algorithm on Angel, you can write your submmit command in the same way.
