### ISSUE TITLE
在“Angel快速入门指南”中有个拼写错误

### ISSUE THREAD

**Issue by EzrealKing** [Tencent/angel#125]
在 docs/tutorials/angel_ps_quick_start.md （即“Angel快速入门指南”）中，第7行有一个拼写错误，
原文：
- 大多数的机器学习算法都可以抽象成向量（Vector）、**矩阵(Martix)**，张量（Tensor）间的运算，用向量、矩阵、张量来表示学习数据和算法模型。

矩阵应该是 **Matrix** 吧。。。

**Comment by TAAAN** [comment]
Thanks, you are very careful, we haved corrected it.
