### ISSUE TITLE
Feature: add y-intercept for logistic regression

### ISSUE THREAD

**Issue by facaiy** [Tencent/angel#142]
It seems that logistic regression doesn't support y-intercept `b`, namely, `w^T x + b`.

I can work on it, but I'm not sure how do maintainers think of the feature: Is it needed?

**Comment by TAAAN** [comment]
In my opinion, b can be considered as the first element of model vector, the follow elements are w. So, if you want to have b, set the first element 1 for every instance:

**Comment by facaiy** [comment]
Sure, @TAAAN . I agree with you.

Adding 1 is a feasible solution in theory, while it seems not common practice in reality. Because the solution is costing (unwanted storage), especially for millions or more samples. Worse still, it's not uncommon to prepare data at first and choose model later.

**Comment by TAAAN** [comment]
@facaiy 
The cost of adding one feature is small when the number of feature is great. 
Or, we can solve this problem in another way, create two PSModels: w and b, the dim of b is 1*1. Each iteration, pull w and b from PS and push the update of w and b to PS.

**Comment by facaiy** [comment]
Yes, @TAAAN . The second solution you suggested above is how the #143 PR is implemented. Do you have time to take a review? Thanks.

**Comment by andyyehoo** [comment]
The PR is Merged. Thanks for your work. :-)
