### ISSUE TITLE
what's ANGEL_HDFS_HOME?

### ISSUE THREAD

**Issue by EternalMoment** [Tencent/angel#158]
Hey guys, thanks a lot for sharing this great work!
Could I ask a simple question: what's ANGEL_HDFS_HOME environmental variable on this [page](https://github.com/Tencent/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md), and where should I point it to?

**Comment by ZunwenYou** [comment]
As showed in [Spark on Angel Quick Start](https://github.com/Tencent/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md) , you must upload a copy of angel-${version}-bin to HDFS.

**Comment by EternalMoment** [comment]
So, it is the location of angel directory uploaded on HDFS. By the way, the markdown on this page is not correctly displayed: angel-${version}-bin is displayed as angel--bin. Do you want me to go ahead and fix it?

**Comment by andyyehoo** [comment]
Yup. Please fixed this with a PR. Thanks :-)
