### ISSUE TITLE
Protobuf 版本问题

### ISSUE THREAD

**Issue by alwayschasing** [Tencent/angel#16]
我安装官方文档要求安装的Protobuf版本为3.3>2.5.0，但是在编译的时候出现错误，提示如下：
 Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project angel-ps-core: Protobuf installation version does not match Protobuf library version

这该怎么办呢？

**Comment by alwayschasing** [comment]
[INFO] angel .............................................. SUCCESS [  0.163 s]
[INFO] angel-ps ........................................... SUCCESS [  2.564 s]
[INFO] angel-ps-core ...................................... FAILURE [  0.234 s]
[INFO] angel-ps-psf ....................................... SKIPPED
[INFO] angel-ps-mllib ..................................... SKIPPED
[INFO] angel-ps-examples .................................. SKIPPED
[INFO] spark-on-angel ..................................... SKIPPED
[INFO] spark-on-angel-core ................................ SKIPPED
[INFO] spark-on-angel-mllib ............................... SKIPPED
[INFO] spark-on-angel-examples ............................ SKIPPED
[INFO] angel-dist ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.185 s
[INFO] Finished at: 2017-06-20T13:54:58+08:00
[INFO] Final Memory: 26M/856M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project angel-ps-core: Protobuf installation version does not match Protobuf library version -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :angel-ps-core

**Comment by paynie** [comment]
Thanks for reports these issues. We strongly recommend you to use the 2.5.0 version of protobuf. The reason can see [issues5](https://github.com/Tencent/angel/issues/5). We will add the description of this problem in the document.

**Comment by luoyexuge** [comment]
我今天装了下  只支持Protobuf 2.50的版本，用3.30的没用，会爆版本不匹配的问题

**Comment by paynie** [comment]
@luoyexuge First you need to install a 2.5.0 version of the protoc, and then need to modify the pom(angel-ps/pom.xml) file inside the protobuf-java version like this
 ```      
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>2.5.0</version>
        </dependency>
```

**Comment by AlexanLee** [comment]
mac环境下做如下安装，我就解决了：
  wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  tar -xzvf protobuf-2.5.0.tar.gz
  pushd protobuf-2.5.0 && ./configure --prefix=/usr/local && make && sudo make install && popd

**Comment by calvinzhan** [comment]
这个在windows上怎么处理呢？

**Comment by iannoying** [comment]
mac 下：
`brew tap homebrew/versions`
`brew install protobuf250`
`brew link --force --overwrite protobuf250`
我这样是可以解决的。
[参考链接](https://stackoverflow.com/questions/21775151/installing-google-protocol-buffers-on-mac)

**Comment by zrss** [comment]
thx @AlexanLee , for windows users, i find the version at there https://github.com/protocolbuffers/protobuf/releases/tag/v2.5.0

**Comment by Song-xx** [comment]
mac M1,上面各种方法都不行啊？ 有没有别的好办法

**Comment by Song-xx** [comment]
> 

> make && sudo make install

make 报错是啥原因啊，我这是mac M1, 报错：
fatal error: too many errors emitted, stopping now [-ferror-limit=]
