### ISSUE TITLE
compare Angel and Spark-on-Angel API

### ISSUE THREAD

**Issue by EternalMoment** [Tencent/angel#166]
Hi developers,

I want to try developing a ML algorithm on angel, but I feel confusing about the Angel API and Spark-on-Angel API. It seems that not all functionalities on Angel is supported on Spark-on-Angel, for example, this [issue](https://github.com/Tencent/angel/issues/10)  

I was wondering if you could briefly discuss the current difference and future development plan when comparing these two API? Maybe, you could give some pros and cons about using each one, so that people can decide which one is better in their situation.

We could discuss this issue here, or include it in docs in the future.

Thanks!

**Comment by ZunwenYou** [comment]
You are right, Spark on Angel API is difference from Angel's.
1. In Spark on Angel, `PSModelPool` will evolve into `MLModel` in Angel.
2. In Angel, the only object in PS is `Matrix`, which contain vector and matrix, and all the operations is designed for `Matrix`. While Spark on Angel will have `Vector` and `Matrix`, and we try to implement operations in Breeze. So, this will be a great difference between angel and spark on angel, though they share the same `PSFunc`.

**Comment by EternalMoment** [comment]
I am interested in implementing the word2vec (specifically, in [Yahoo's parallel structure](https://arxiv.org/abs/1606.08495)). I believe your Angel design has paid attention to this paper at the beginning. However, before I start, I was wondering if you guys think there is any critical and inherent problem with current Angel-on-Spark API that might prevents me from doing so. 
If it's not something you guys are working on, then don't worry, and I will figure out myself.

**Comment by andyyehoo** [comment]
API is not  a problem. Just go ahead with Word2Vec.

**Comment by EternalMoment** [comment]
I think I can't implement the algorithm on Spark API without matrix type parameter. The parameter in this model is around 20M * 300 size matrix partitioned by column. I guess requesting 300 vectors are not the right way to hack through this problem.

**Comment by hbghhy** [comment]
I also used to try implement paper in Spark API. The Yahoo's implementation needs some dot and other vector operation in PSMatrix. Though the Spark API has matrix now. It seems they can only be push, pull, and update some row by mapFuc. It seems still hard to implement it. Maybe implement it with origin angel is available, but handle the input and broadcast the exptable and wordmap seems to be a problem too.

**Comment by andyyehoo** [comment]
@EternalMoment It should be OK for you now

@hbghhy This still need improve. PR is welcome.
