### ISSUE TITLE
Fix local_run.md

### ISSUE THREAD

**Issue by gammaliu** [Tencent/angel#172]
the script 
```
./angel-example com.tencent.angel.example.SgdLRLocalExample
```
should be
```
./angel-example com.tencent.angel.example.ml.SGDLRLocalExample
```

**Comment by andyyehoo** [comment]
Thanks. Could u pls fix it with a PR?  :-)

**Comment by boolyahoo** [comment]
I run the command ./angel-example com.tencent.angel.example.ml.SGDLRLocalExample but get an error of "Could not find or load main class com.tencent.angel.example.ml.SgdLRLocalExample", what's going wrong?
