### ISSUE TITLE
mvn编译问题

### ISSUE THREAD

**Issue by yunguangwang891017** [Tencent/angel#179]
在用mvn编译angel 的时候直接报错，错误信息如下：
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.tencent.angel:angel-ps-mllib:[unknown-version]: Could not transfer artifact com.tencent.angel:angel-ps:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 21, column 11
[FATAL] Non-resolvable parent POM for com.tencent.angel:angel-ps-psf:[unknown-version]: Failure to transfer com.tencent.angel:angel-ps:pom:1.2.0 from http://172.16.100.98/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact com.tencent.angel:angel-ps:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 22, column 11
[FATAL] Non-resolvable parent POM for com.tencent.angel:angel-ps-examples:[unknown-version]: Failure to transfer com.tencent.angel:angel-ps:pom:1.2.0 from http://172.16.100.98/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact com.tencent.angel:angel-ps:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 22, column 11
[FATAL] Non-resolvable parent POM for com.tencent.angel:spark-on-angel:[unknown-version]: Could not transfer artifact com.tencent.angel:angel:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 22, column 10
[FATAL] Non-resolvable parent POM for com.tencent.angel:angel-dist:[unknown-version]: Failure to transfer com.tencent.angel:angel:pom:1.2.0 from http://172.16.100.98/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact com.tencent.angel:angel:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 24, column 11
 @ 
[ERROR] The build could not read 5 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.tencent.angel:angel-ps-mllib:[unknown-version] (/home/wangyunguang/angel1/angel-ps/mllib/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.tencent.angel:angel-ps-mllib:[unknown-version]: Could not transfer artifact com.tencent.angel:angel-ps:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 21, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project com.tencent.angel:angel-ps-psf:[unknown-version] (/home/wangyunguang/angel1/angel-ps/psf/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.tencent.angel:angel-ps-psf:[unknown-version]: Failure to transfer com.tencent.angel:angel-ps:pom:1.2.0 from http://172.16.100.98/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact com.tencent.angel:angel-ps:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 22, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project com.tencent.angel:angel-ps-examples:[unknown-version] (/home/wangyunguang/angel1/angel-ps/examples/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.tencent.angel:angel-ps-examples:[unknown-version]: Failure to transfer com.tencent.angel:angel-ps:pom:1.2.0 from http://172.16.100.98/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact com.tencent.angel:angel-ps:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 22, column 11 -> [Help 2]
[ERROR]   
[ERROR]   The project com.tencent.angel:spark-on-angel:[unknown-version] (/home/wangyunguang/angel1/spark-on-angel/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.tencent.angel:spark-on-angel:[unknown-version]: Could not transfer artifact com.tencent.angel:angel:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 22, column 10 -> [Help 2]
[ERROR]   
[ERROR]   The project com.tencent.angel:angel-dist:[unknown-version] (/home/wangyunguang/angel1/dist/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.tencent.angel:angel-dist:[unknown-version]: Failure to transfer com.tencent.angel:angel:pom:1.2.0 from http://172.16.100.98/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact com.tencent.angel:angel:pom:1.2.0 from/to nexus (http://172.16.100.98/nexus/content/groups/public/): Connect to 172.16.100.98:80 [/172.16.100.98] failed: Connection timed out and 'parent.relativePath' points at wrong local POM @ line 24, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by paynie** [comment]
Maybe you need pull the latest code of branch-1.2.0
