### ISSUE TITLE
PSAttempt_0_0 failed due to: heartbeat timeout

### ISSUE THREAD

**Issue by alleyZ** [Tencent/angel#18]
* ENV:` hadoop2.7.2`  `jdk1.8`
* Error: `PSAttempt_0_0 failed due to: heartbeat timeout`
* command: 
```
./angel-submit \
--angel.app.submit.class "com.tencent.angel.ml.classification.lr.LRRunner"\
 	--angel.train.data.path "hdfs://hd-23:6000/angel/data" \
 	--angel.log.path "hdfs://hd-23:6000/angel/log1" \
 	--angel.save.model.path "hdfs://hd-23:6000/angel/model1" \
 	--action.type train \
 	--ml.data.type libsvm \
 	--ml.feature.num 1024 \
	--angel.am.env JAVA_HOME="/usr/local/lib/jdk1.8.0_77",PATH="/usr/local/lib/jdk1.8.0_77/bin:$PATH" \
	--angel.worker.env JAVA_HOME="/usr/local/lib/jdk1.8.0_77",PATH="/usr/local/lib/jdk1.8.0_77/bin:$PATH" \
	--angel.ps.env JAVA_HOME="/usr/local/lib/jdk1.8.0_77",PATH="/usr/local/lib/jdk1.8.0_77/bin:$PATH" \
	--angel.am.heartbeat.interval.ms 10000 \
	--angel.worker.heartbeat.interval.ms 10000 \
	--angel.ps.heartbeat.interval.ms 10000 \
	--angel.worker.max-attempts 2 \
	--angel.ps.max-attempts 2 \
 	--angel.job.name test 
```
* log: [The Log](https://github.com/alleyZ/tsp/blob/master/angel.log) 

**Can you tell me how to solve it, please?**

**Comment by paynie** [comment]
Thanks for reports these issues.  PS startup failed, you can find error message in PS log using methods in  [FAQ](https://github.com/Tencent/angel/wiki/Angel%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by alleyZ** [comment]
我在`hdfs://hd-29:8020/tmp/logs/yarn/logs/application_1497605921396_0037`看到了两个日志：
`hd-27_8041` `hd-29_8041` ， 查看以后得知`PS`未启动的原因是`java.lang.NoClassDefFoundError: com/google/protobuf/ProtocolStringList`导致，随即检查了编译版本内容，发现使用的`protobuf-java`版本为`-2.6.1`；猜测可能是此处问题(master版本使用的是`2.5.0` 之前使用`v-1.0.0`分支)； 重新检出master的代码进行编译，再次运行成功!

**Comment by Mr-Phoebe** [comment]
@alleyZ 为什么我这里只能用protobuf 2.6.1 编译 = =
它显示
```
[INFO] Protobuf dependency version 2.6.1
[INFO] 'protoc' executable version 2.6.1
```

**Comment by alleyZ** [comment]
@Mr-Phoebe 我安装的`protoc-2.5.0-win32.zip`，`master`主干的依赖是`2.5.0`，编译时:
```
[INFO] --- protobuf-maven-plugin:0.6.3:run (default) @ angel-ps-core ---
[INFO] Protobuf dependency version 2.5.0
[INFO] 'protoc' executable version 2.5.0
[INFO] Input directories:
```
最终生成的zip包中包含`protobuf-java-2.5.0.jar`

**Comment by paynie** [comment]
@Mr-Phoebe we update the document about source compile: add attention about protobuf. https://github.com/Tencent/angel/blob/branch-1.0.0/docs/deploy/source_compile.md
