### ISSUE TITLE
SparseLRWithSGD.runPSSGD  is slower than that spark

### ISSUE THREAD

**Issue by AugustoYao** [Tencent/angel#194]
Hi, I'm testing angel-on-spark with three machines , 32GB, 24 CPU vcores per node.  When running SparseLRWithSGD.runSGD, runPSSGD,  runPSSGD is slower than runSGD. I wonder if anyone have the same problem?

**Comment by ZunwenYou** [comment]
Please provide more information about Spark/Angel conf and the size of data set(instance count and feature count).

**Comment by AugustoYao** [comment]
Well, spark's version is 2.1.0, while angel's version is 1.0.0. And my data set has 1M instances and 500K features, actually for each instance, there's only 250 features not equal to 0.  Some running parameters are shown below:
--conf spark.ps.mode=YARN 
--conf spark.yarn.am.cores=2 
--conf spark.yarn.am.memory=4g 
--conf spark.ps.instances=3 
--conf spark.ps.cores=2 
--conf spark.ps.memory=2g 
--driver-memory 12g 
--driver-cores 2 
--num-executors 12 
--executor-cores 2 
--executor-memory 4g
