### ISSUE TITLE
object generated is not a member of package com.tencent.angel.protobuf

### ISSUE THREAD

**Issue by ryan-bin** [Tencent/angel#207]
hi, I run  LOCAL Examples:
`./angel-example com.tencent.angel.example.ml.SGDLRLocalExample`
is ok.
but when i try to run the local example from angel-ps/examples , I get the message:
`Error:(13, 35) object generated is not a member of package com.tencent.angel.protobuf
import com.tencent.angel.protobuf.generated.MLProtos
                                  ^
Error:(127, 27) not found: value MLProtos
  def setRowType(rowType: MLProtos.RowType):this.type = {
                          ^
Error:(22, 8) object generated is not a member of package com.tencent.angel.protobuf
import com.tencent.angel.protobuf.generated.MLProtos;
       ^
Error:(231, 26) not found: value MLProtos
  public void setRowType(MLProtos.RowType rowType) {
                         ^`
help me, plz!

**Comment by paynie** [comment]
Is you protoc version 2.5.0?

**Comment by ryan-bin** [comment]
yes, Protobuf=2.5.0

**Comment by paynie** [comment]
Are there any compile problems? You can check package "com.tencent.angel.protobuf.generated" in you angel-ps-core-${version}.jar
