### ISSUE TITLE
package com.tencent.angel.protobuf.generated.* does not exist.

### ISSUE THREAD

**Issue by ghandzhipeng** [Tencent/angel#217]
These files are used in AngelClient.java, MasterProtocol.java, AngelYarnClient, etc. 

However, they are not included in the current repository. 

Thanks.

**Comment by ghandzhipeng** [comment]
The files needed are generated in target file.

**Comment by maozida880** [comment]
这个怎么实现的，遇到了同样的问题

**Comment by Song-xx** [comment]
> 

Hello, which target file, please?

**Comment by wangcaihua** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
