### ISSUE TITLE
[MLLib] FTRL with Spark Streaming

### ISSUE THREAD

**Issue by andyyehoo** [Tencent/angel#224]
**FTRL Algorithms with Spark Streaming of Angel**

**Comment by edgue** [comment]
FTRL is an online learning algorithm which has excellent sparsity and convergence properties.And the FTRL-Proximal can be seen as a hybrid of FOBOS and RDA algorithms and significantly outperforms on a large, realworld dataset.I think it can be accomplished by spark streaming of angel.The spark streaming is for online learning and angel ps is for pulling the Z model and N model and pushing their increments.

**Comment by andyyehoo** [comment]
It's implemented in [1.3.0] (https://github.com/Tencent/angel/releases/tag/v1.3.0). Please check.
