### ISSUE TITLE
com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector

### ISSUE THREAD

**Issue by lizhqing** [Tencent/angel#229]
#! /bin/bash
source ./spark-on-angel-env.sh
$SPARK_HOME/bin/spark-submit \
    --master yarn-cluster \
    --conf spark.ps.jars=$SONA_ANGEL_JARS \
    --conf spark.ps.instances=10 \
    --conf spark.ps.cores=2 \
    --conf spark.ps.memory=6g \
    --queue g_teg_angel.g_teg_angel-offline \
    --jars $SONA_SPARK_JARS \
    --name "BreezeSGD-spark-on-angel" \
    --driver-memory 10g \
    --num-executors 10 \
    --executor-cores 2 \
    --executor-memory 4g \
    --class com.tencent.angel.spark.examples.ml.BreezeSGD \
    ./../lib/spark-on-angel-examples-${ANGEL_VERSION}.jar
angel1.2.0 running report some errors ：
yarn logs -applicationId application_1508120755275_0005 |grep Exception
17/10/16 11:05:21 ERROR ApplicationMaster: User class threw exception: com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector
com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector
17/10/16 11:05:21 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector)
17/10/16 11:05:21 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector)
17/10/16 11:04:15 ERROR ApplicationMaster: User class threw exception: com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector
com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector
17/10/16 11:04:15 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: com.tencent.angel.exception.AngelException: Don't try to clone a Decorated PSVector)

any help？

**Comment by andyyehoo** [comment]
Thanks. We will look into it soon.

BTW: What's your Spark Version?
