### ISSUE TITLE
64bit feature id supported?

### ISSUE THREAD

**Issue by ericzhang-cn** [Tencent/angel#262]
Is angel support 64bit feature id? I find that both data parser and PSModel were hard code for only 32bit feature id

**Comment by paynie** [comment]
Thanks. 
Some algorithm utils need to improved to support 64-bit feature now.

**Comment by paynie** [comment]
We will improve it in next version.

**Comment by andyyehoo** [comment]
It‘s done in [Release-1.4.0](https://github.com/Tencent/angel/releases/tag/v1.4.0)
