### ISSUE TITLE
hadoop 集群的java 版本是java7， 可以运行angel 嘛？

### ISSUE THREAD

**Issue by tankle** [Tencent/angel#264]

**Comment by andyyehoo** [comment]
It can be done in this way. Check [this](https://github.com/Tencent/angel/wiki/%E5%B7%A5%E7%A8%8B%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3-%E5%A6%82%E6%9E%9C%E6%88%91%E7%9A%84hadoop%E9%9B%86%E7%BE%A4%E4%BD%BF%E7%94%A8%E7%9A%84jdk%E7%89%88%E6%9C%AC%E6%98%AF17%E6%88%91%E5%BA%94%E8%AF%A5%E6%80%8E%E4%B9%88%E5%9C%A8%E4%B8%8A%E9%9D%A2%E8%BF%90%E8%A1%8Cangel).

**Comment by tankle** [comment]
- 上传JDK1.8到Hadoop计算节点
  集群中 计算节点没有权限上传数据
