### ISSUE TITLE
How to run LDA demo？

### ISSUE THREAD

**Issue by Coffeexiudou** [Tencent/angel#277]
sry，Im a  newer, I find there are GBDT,LR,MF,etc  but without LDA, where can I find a more detail Tutorial？

**Comment by leleyu** [comment]
hi, you can find a UT test of LDA through https://github.com/Tencent/angel/blob/master/angel-ps/mllib/src/test/java/com/tencent/angel/ml/LDA/LDATest.scala.

In distributed environment, you can set the parameters according to document of LDA https://github.com/Tencent/angel/blob/master/docs/algo/lda_on_angel.md.
