### ISSUE TITLE
how can i use model generated by Angel-PS

### ISSUE THREAD

**Issue by ryan7th** [Tencent/angel#278]
hi, i'm a fresh man to angel.
i run the example to generate my model ,but i do not know how to use model on my service to predict ~ ~ 
any body give me a suggestion? thanks

**Comment by paynie** [comment]
You can use model load tools describe in https://github.com/Tencent/angel/blob/master/docs/assistant/ModelLoader.md

**Comment by ryan7th** [comment]
@paynie  but how can i use that on my online system to get the predict
