### ISSUE TITLE
submitted by user  to unknown queue: g_teg_angel.g_teg_angel-offline

### ISSUE THREAD

**Issue by gujingit** [Tencent/angel#279]
I run ./SONA-example, and this is the problem.(Spark On Angel)
18/01/07 15:26:20 INFO yarn.Client: Application report for application_1515233069677_0013 (state: FAILED)
18/01/07 15:26:20 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: Application application_1515233069677_0013 submitted by user root to unknown queue: g_teg_angel.g_teg_angel-offline
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: g_teg_angel.g_teg_angel-offline
	 start time: 1515309979243
	 final status: FAILED
	 tracking URL: http://ubuntu1:8088/proxy/application_1515233069677_0013/

**Comment by ZunwenYou** [comment]
The user and queue configuration of Spark must changed based on your own Yarn platform.
