### ISSUE TITLE
64位的feature id 啥时候支持?

### ISSUE THREAD

**Issue by witgo** [Tencent/angel#282]
我打算把https://github.com/cloudml/zen 项目的算法迁移到angel-ps 上, 需要自己实现一个基于angel-ps + Spark的图计算引擎.

**Comment by andyyehoo** [comment]
It's coming in 1.4.0. We are releasing it now. The code is already there. 

:-)

**Comment by witgo** [comment]
This is a good news.

**Comment by andyyehoo** [comment]
It‘s done in [Release-1.4.0](https://github.com/Tencent/angel/releases/tag/v1.4.0)

**Comment by witgo** [comment]
@andyyehoo  从`PSContext` 类来看一个矩阵行数还是`Int` 型.
