### ISSUE TITLE
failed to submit angel job

### ISSUE THREAD

**Issue by EstaWang** [Tencent/angel#283]
my command is like this:
./bin/angel-submit --action.type train --angel.app.submit.class com.tencent.angel.example.quickStart.QSLRRunner  --angel.train.data.path /user/zhanq/ml/training_data --angel.save.model.path /user/zhanq/ml/model --ml .epoch.num 10 --ml.feature.num 10000 --ml.data.type dummy --ml.learn.rate 0.001 --angel.workergroup.number 2 --angel.worker.memory.mb 4000  --angel.worker.task.number 2 --angel.ps.number 1 --angel.ps.memory.mb 5000 --angel.job.name QSLR -- angel.deploy.mode YARN

But I get error information:
18/01/15 18:23:28 INFO client.AngelClient: job is finished! status: J_FAILED
18/01/15 18:23:28 ERROR client.AngelClient:  detail is killed and failed workergroup is over tolerate 0.01
failed workergroups:
WorkerGroup_0. Worker_0_0 failed. WorkerAttempt_0_0_0 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]
WorkerAttempt_0_0_1 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]
WorkerAttempt_0_0_2 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]
WorkerAttempt_0_0_3 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]

18/01/15 18:23:28 INFO impl.YarnClientImpl: Killed application application_1516001894701_0017
18/01/15 18:23:28 FATAL utils.AngelRunJar: submit job failed 
com.tencent.angel.exception.AngelException: app run failed,  detail is killed and failed workergroup is over tolerate 0.01
failed workergroups:
WorkerGroup_0. Worker_0_0 failed. WorkerAttempt_0_0_0 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]
WorkerAttempt_0_0_1 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]
WorkerAttempt_0_0_2 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]
WorkerAttempt_0_0_3 failed due to: taskid=task_0, state=FAILED, diagnostics=[task runner errorPre-Process Error.]taskid=task_1, state=FAILED, diagnostics=[task runner errorPre-Process Error.]

	at com.tencent.angel.client.AngelClient.waitForCompletion(AngelClient.java:290)
	at com.tencent.angel.ml.MLRunner$class.train(MLRunner.scala:50)
	at com.tencent.angel.example.quickStart.QSLRRunner.train(QSLRRunner.scala:23)
	at com.tencent.angel.example.quickStart.QSLRRunner.train(QSLRRunner.scala:28)
	at com.tencent.angel.ml.MLRunner$class.submit(MLRunner.scala:95)
	at com.tencent.angel.example.quickStart.QSLRRunner.submit(QSLRRunner.scala:23)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:67)
	at com.tencent.angel.utils.AngelRunJar$1.run(AngelRunJar.java:54)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1835)
	at com.tencent.angel.utils.AngelRunJar.submit(AngelRunJar.java:54)
	at com.tencent.angel.utils.AngelRunJar.main(AngelRunJar.java:38)

Is there anything I missed? Or am I doing anything wrong?

**Comment by EstaWang** [comment]
It turns out that I set wrong parameters and training data.

**Comment by chuanjie** [comment]
Excuse me. I meet the same error report, but i can not find the problem could you tell me the problem in your case? Thx.
