### ISSUE TITLE
LDAModel do not implement predict method, it can not predict unobserved samples

### ISSUE THREAD

**Issue by rockqgf** [Tencent/angel#295]
I found LDAModel's predict method just returns null, it can not infer topics distribution except training corpus.

**Comment by leleyu** [comment]
The inference of topic distribution for  new documents is accomplished by running LDAPredictTask.

**Comment by rockqgf** [comment]
@leleyu I ran LDAPredictTask, set angel.predict.data.path, angel.predict.out.path,angel.save.model.path and save.doc.topic true,  but I can not get any results。
