### ISSUE TITLE
Different base of libsvm index between spark_on_angel and angel

### ISSUE THREAD

**Issue by Morrissss** [Tencent/angel#298]
[spark_on_angel (1-based)](https://github.com/Tencent/angel/blob/master/spark-on-angel/mllib/src/main/scala/com/tencent/angel/spark/ml/util/DataLoader.scala#L131)

[angel (0-based)](https://github.com/Tencent/angel/blob/master/angel-ps/mllib/src/main/java/com/tencent/angel/ml/utils/DataParser.scala#L74)

Should they keep consistent?

**Comment by wangcaihua** [comment]
Thank you for submit issue, we have notice the problem, we will fix it next iteration. the change will base on: https://stats.stackexchange.com/questions/61328/libsvm-data-format
