### ISSUE TITLE
how to use FTRL on spark ?

### ISSUE THREAD

**Issue by lebron374** [Tencent/angel#299]
已经看了文档，但是似乎没有特别明白。 https://github.com/Tencent/angel/blob/master/docs/deploy/run_on_yarn.md
是指将angel的zip文件解压缩后放到指定机器（该机器能够访问hadoop/spark集群），然后就可以通过spark-submit提交就可以了么

**Comment by ZunwenYou** [comment]
https://github.com/Tencent/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md

**Comment by ZunwenYou** [comment]
Have a look at this tutorial, 
https://github.com/Tencent/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md

**Comment by edgue** [comment]
You can  read https://github.com/Tencent/angel/blob/master/docs/algo/ftrl_lr_spark.md for FTRL on Spark reference

**Comment by Luffky** [comment]
额，我能不能不在yarn集群上事先安装angel，因为我没有yarn集群的控制权限，而是把所有的angel依赖包和我的项目打包到一个jar文件中，再用spark-submit提交到集群上？但是这样在PSContext初始化的时候总是报各种错

**Comment by ZunwenYou** [comment]
Please join our angel QQ group: 20171688, any problem can be proposed in the QQ group
