### ISSUE TITLE
yarn 模式下使用spark on angel报错

### ISSUE THREAD

**Issue by Luffky** [Tencent/angel#312]
在yarn模式下如果没有依赖的jar，不显式设定spark.ps.jars这个参数，那么这个参数的value就会是空字符串，然后在启动PSContext的时候，AngelYarnClient里copyAndConfigureFiles方法会解析这一项并且调用Path方法，从而产生了Path不能为empty String的异常，请问有什么解决办法吗。
异常栈如下
![pasted graphic](https://user-images.githubusercontent.com/26293823/38493195-e6fdf96e-3c23-11e8-909f-bbedfaf9ce7f.jpg)

**Comment by ZunwenYou** [comment]
`spark.ps.jars` conf must be set when use spark on angel.
