### ISSUE TITLE
User class threw exception: java.lang.NoSuchMethodError: breeze.linalg.DenseVector$.space_Double()Lbreeze/math/MutableFiniteCoordinateField;

### ISSUE THREAD

**Issue by liuzx32** [Tencent/angel#317]
angel-1.5.0运行SONA-example脚本报这个Error

**Comment by ZunwenYou** [comment]
Spark on Angel is based on Spark 2.1.0 and breeze_2.11-0.13. 
This is spark on angel quick start, https://github.com/Tencent/angel/blob/master/docs/tutorials/spark_on_angel_quick_start.md

**Comment by liuzx32** [comment]
Yes I know, my local spark is 2.0.1 and  breeze_2.11-0.11.
But there is no spark version  in spark_on_angel_quick_start.md.
