### ISSUE TITLE
There is data dir, but I don't know the mapping to the algo?

### ISSUE THREAD

**Issue by liuzx32** [Tencent/angel#323]

**Comment by wangcaihua** [comment]
not sure which data directory you meant. 
we do have multiple data directories for different purposes, sorry to get you confused.

I have taken a double check, only two datasets (a9a.test/a9a.train) are required to be assign to algorithm. 

a9a.test/a9a.train are binary classification datasets, you can employ them in LR, FM, SVM and so on.
pls. refers to https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html

**Comment by liuzx32** [comment]
I get it, Thank you~
