### ISSUE TITLE
Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project angel-ps-core: Cannot execute 'protoc': Cannot run program "protoc": CreateProcess  error=2

### ISSUE THREAD

**Issue by githubchencai** [Tencent/angel#343]
idea 2016.2 mvn compile problem;
check protobuf ready download dependency

[ERROR] Failed to execute goal com.github.igor-petruk.protobuf:protobuf-maven-plugin:0.6.3:run (default) on project angel-ps-core: Cannot execute 'protoc': Cannot run program "protoc": CreateProcess
 error=2, 系统找不到指定的文件。 -> [Help 1]

**Comment by paynie** [comment]
You should install protoc tool first like this : http://www.aboutyun.com/thread-8212-1-1.html

**Comment by githubchencai** [comment]
think you,issues solved
