### ISSUE TITLE
spark on angel run  ${ANGEL_HOME}/bin/SONA-example  error:init PSContext failed;java.net.UnknownHostException: angel

### ISSUE THREAD

**Issue by githubchencai** [Tencent/angel#344]
SONA_ANGEL_JARS: hdfs://angel/lib/fastutil-7.1.0.jar,hdfs://angel/lib/htrace-core-2.05.jar,hdfs://angel/lib/sizeof-0.3.0.jar,hdfs://angel/lib/kryo-shaded-4.0.0.jar,hdfs://angel/lib/minlog-1.3.0.jar,hdfs://angel/lib/sketches-core-0.8.1.jar,hdfs://angel/lib/memory-0.8.1.jar,hdfs://angel/lib/commons-pool-1.6.jar,hdfs://angel/lib/angel-ps-core-1.5.1.jar,hdfs://angel/lib/angel-ps-mllib-1.5.1.jar,hdfs://angel/lib/angel-ps-examples-1.5.1.jar,hdfs://angel/lib/angel-ps-psf-1.5.1.jar,hdfs://angel/lib/spark-on-angel-mllib-1.5.1-ps.jar,hdfs://angel/lib/spark-on-angel-examples-1.5.1-ps.jar,hdfs://angel/lib/scala-library-2.11.8.jar
SONA_SPARK_JARS: /usr/local/angel/lib/fastutil-7.1.0.jar,/usr/local/angel/lib/htrace-core-2.05.jar,/usr/local/angel/lib/sizeof-0.3.0.jar,/usr/local/angel/lib/kryo-shaded-4.0.0.jar,/usr/local/angel/lib/minlog-1.3.0.jar,/usr/local/angel/lib/sketches-core-0.8.1.jar,/usr/local/angel/lib/memory-0.8.1.jar,/usr/local/angel/lib/commons-pool-1.6.jar,/usr/local/angel/lib/angel-ps-core-1.5.1.jar,/usr/local/angel/lib/angel-ps-mllib-1.5.1.jar,/usr/local/angel/lib/angel-ps-examples-1.5.1.jar,/usr/local/angel/lib/angel-ps-psf-1.5.1.jar,/usr/local/angel/lib/spark-on-angel-core-1.5.1.jar,/usr/local/angel/lib/spark-on-angel-mllib-1.5.1.jar
Warning: Master yarn-cluster is deprecated since 2.0. Please use master "yarn" with specified deploy mode instead.
18/05/11 18:10:18 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/05/11 18:10:19 INFO client.RMProxy: Connecting to ResourceManager at bdm/192.168.1.232:8032
18/05/11 18:10:19 INFO yarn.Client: Requesting a new application from cluster with 5 NodeManagers
18/05/11 18:10:19 INFO yarn.Client: Verifying our application has not requested more than the maximum memory capability of the cluster (8192 MB per container)
18/05/11 18:10:19 INFO yarn.Client: Will allocate AM container, with 6758 MB memory including 614 MB overhead
18/05/11 18:10:19 INFO yarn.Client: Setting up container launch context for our AM
18/05/11 18:10:19 INFO yarn.Client: Setting up the launch environment for our AM container
18/05/11 18:10:19 INFO yarn.Client: Preparing resources for our AM container
18/05/11 18:10:21 WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
18/05/11 18:10:25 INFO yarn.Client: Uploading resource file:/data/spark/tmp/spark-5ecf2923-e811-4746-83a2-3cfbe7e0ac5b/__spark_libs__5728289740946286277.zip -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/__spark_libs__5728289740946286277.zip
18/05/11 18:10:47 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/spark-on-angel-examples-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/spark-on-angel-examples-1.5.1.jar
18/05/11 18:10:49 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/fastutil-7.1.0.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/fastutil-7.1.0.jar
18/05/11 18:10:51 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/htrace-core-2.05.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/htrace-core-2.05.jar
18/05/11 18:10:52 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/sizeof-0.3.0.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/sizeof-0.3.0.jar
18/05/11 18:10:52 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/kryo-shaded-4.0.0.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/kryo-shaded-4.0.0.jar
18/05/11 18:10:52 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/minlog-1.3.0.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/minlog-1.3.0.jar
18/05/11 18:10:52 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/sketches-core-0.8.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/sketches-core-0.8.1.jar
18/05/11 18:10:52 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/memory-0.8.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/memory-0.8.1.jar
18/05/11 18:10:52 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/commons-pool-1.6.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/commons-pool-1.6.jar
18/05/11 18:10:53 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/angel-ps-core-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/angel-ps-core-1.5.1.jar
18/05/11 18:10:53 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/angel-ps-mllib-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/angel-ps-mllib-1.5.1.jar
18/05/11 18:10:53 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/angel-ps-examples-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/angel-ps-examples-1.5.1.jar
18/05/11 18:10:53 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/angel-ps-psf-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/angel-ps-psf-1.5.1.jar
18/05/11 18:10:54 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/spark-on-angel-core-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/spark-on-angel-core-1.5.1.jar
18/05/11 18:10:54 INFO yarn.Client: Uploading resource file:/usr/local/angel/lib/spark-on-angel-mllib-1.5.1.jar -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/spark-on-angel-mllib-1.5.1.jar
18/05/11 18:10:56 INFO yarn.Client: Uploading resource file:/data/spark/tmp/spark-5ecf2923-e811-4746-83a2-3cfbe7e0ac5b/__spark_conf__3423178392475011636.zip -> hdfs://digcluster/user/hdpusr/.sparkStaging/application_1526026840251_0008/__spark_conf__.zip
18/05/11 18:11:14 INFO spark.SecurityManager: Changing view acls to: hdpusr
18/05/11 18:11:14 INFO spark.SecurityManager: Changing modify acls to: hdpusr
18/05/11 18:11:14 INFO spark.SecurityManager: Changing view acls groups to: 
18/05/11 18:11:14 INFO spark.SecurityManager: Changing modify acls groups to: 
18/05/11 18:11:14 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hdpusr); groups with view permissions: Set(); users  with modify permissions: Set(hdpusr); groups with modify permissions: Set()
18/05/11 18:11:14 INFO yarn.Client: Submitting application application_1526026840251_0008 to ResourceManager
18/05/11 18:11:14 INFO impl.YarnClientImpl: Submitted application application_1526026840251_0008
18/05/11 18:11:15 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:15 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.hdpusr
	 start time: 1526033474100
	 final status: UNDEFINED
	 tracking URL: http://bdm:8088/proxy/application_1526026840251_0008/
	 user: hdpusr
18/05/11 18:11:16 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:17 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:18 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:19 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:20 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:21 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:22 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:23 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:24 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:25 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:26 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:27 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:28 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:29 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:11:30 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:30 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 192.168.1.237
	 ApplicationMaster RPC port: 0
	 queue: root.hdpusr
	 start time: 1526033474100
	 final status: UNDEFINED
	 tracking URL: http://bdm:8088/proxy/application_1526026840251_0008/
	 user: hdpusr
18/05/11 18:11:31 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:32 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:33 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:34 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:35 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:36 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:37 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:38 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:39 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:40 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:41 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:42 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:43 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:44 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:45 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:46 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:47 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:48 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:49 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:50 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:51 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:52 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:53 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:54 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:55 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:56 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:57 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:58 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:11:59 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:00 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:01 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:01 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: root.hdpusr
	 start time: 1526033474100
	 final status: UNDEFINED
	 tracking URL: http://bdm:8088/proxy/application_1526026840251_0008/
	 user: hdpusr
18/05/11 18:12:02 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:03 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:04 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:05 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:06 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:07 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:08 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:09 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:10 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:11 INFO yarn.Client: Application report for application_1526026840251_0008 (state: ACCEPTED)
18/05/11 18:12:12 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:12 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 192.168.1.237
	 ApplicationMaster RPC port: 0
	 queue: root.hdpusr
	 start time: 1526033474100
	 final status: UNDEFINED
	 tracking URL: http://bdm:8088/proxy/application_1526026840251_0008/
	 user: hdpusr
18/05/11 18:12:13 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:14 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:15 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:16 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:17 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:18 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:19 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:20 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:21 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:22 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:23 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:24 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:25 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:26 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:27 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:28 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:29 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:30 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:31 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:32 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:33 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:34 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:35 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:36 INFO yarn.Client: Application report for application_1526026840251_0008 (state: RUNNING)
18/05/11 18:12:37 INFO yarn.Client: Application report for application_1526026840251_0008 (state: FINISHED)
18/05/11 18:12:37 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: N/A
	 ApplicationMaster host: 192.168.1.237
	 ApplicationMaster RPC port: 0
	 queue: root.hdpusr
	 start time: 1526033474100
	 final status: FAILED
	 tracking URL: http://bdm:8088/proxy/application_1526026840251_0008/A
	 user: hdpusr
Exception in thread "main" org.apache.spark.SparkException: Application application_1526026840251_0008 finished with failed status
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1167)
	at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1213)
	at org.apache.spark.deploy.yarn.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/05/11 18:12:37 INFO util.ShutdownHookManager: Shutdown hook called
18/05/11 18:12:37 INFO util.ShutdownHookManager: Deleting directory /data/spark/tmp/spark-5ecf2923-e811-4746-83a2-3cfbe7e0ac5b

**Comment by Phoenixinfire** [comment]
你解决了吗？怎么解决的？
