### ISSUE TITLE
Support newer version of protobuf

### ISSUE THREAD

**Issue by zuowang** [Tencent/angel#5]
The version of protobuf is out of date(2.6.1, release in year 2014)

**Comment by paynie** [comment]
We use the 2.6.1 version of the Protobuf primarily to be compatible with the Yarn. Angel runs  on Yarn platform, and our Yarn is currently using the 2.6.1 version of Protobuf now. If we use a different version in Angel, our Master (Yarn's AppMaster) must load two versions of Protobuf, which may cause some compatibility issues.  But if your Yarn platform uses an newer version, you can also use it in Angel.

**Comment by paynie** [comment]
Protobuf version has been change to 2.5.0, which is compatible with official distribution packs of hadoop/spark.
