### ISSUE TITLE
[GBDT] The purposes of using parameter server in GBDT

### ISSUE THREAD

**Issue by guolinke** [Tencent/angel#7]
既然文档都是中文，那就直接用中文吧。

GBDT的文档提到使用PS的原因:
> 
> 超大模型： GBDT用到的梯度直方图的大小与特征数量成正比，对于高维大数据集，梯度直方图会非常大，Angel将梯度直方图切分到到多个PS节点上存储，可以解决了高维度模型在汇总参数时的单点瓶颈问题。
> 
> 通讯开销：：合理地存储和切分全局梯度直方图，每个Worker不需要获取完整的全局梯度直方图，使用这种方法，大大减小了通信开销，加速了汇总局部梯度直方图的速度
> 
> 两阶段树分裂算法： 在寻找最佳分裂点时，可以在多个PS节点上并行进行，只需要将局部最优分裂点返回给Worker，通信开销几乎可以忽略不计。

对于“超大模型”这一点，并不是很赞同。因为每个worker上构造的“部分直方图"和”全局直方图“的大小是一样的（每个worker各有一部分水平切分的数据，所以构造的直方图还是full feature的）。使用PS并不能减少worker的内存占用，没有解决高维数据的问题。

对于“通讯开销” 和 “两阶段树分裂算法”这两点，有没有PS都可以做到，比如LightGBM直接用“Reduce Scatter” 实现了不同worker合并不同的直方图，然后同步最优分割点，效果是等价的。参阅：https://github.com/Microsoft/LightGBM/wiki/Features#data-parallel-in-lightgbm 

另外，第二点中，应该是"每个PS不需要获取完整的全局梯度直方图"？ 

如有理解错误，欢迎指正。

**Comment by bluesjjw** [comment]
感谢提出的意见。

使用PS的目的并不是为了减少worker的内存占用，而是为了加速直方图的汇总。MLlib的map-reduce方式需要在单点汇总梯度直方图，而xgboost和lightgbm使用的tree allreduce需要多步传输。对于高维数据，这两种方式的可扩展性受限。

“通讯开销” 和 “两阶段树分裂算法”的问题，当然可以在其他的架构下实现，我们是针对PS的架构做了特定的实现。

第二点中，每个PS不需要获取完整的全局梯度直方图，每个Worker也不需要获取完整的全局梯度直方图。详见我们的论文 TencentBoost: A Gradient Boosting Tree System with Parameter Server

除了PS架构下的网络优化，其他算法层面的优化也会在后续的论文中详细给出。

系统刚刚开源，还在持续优化和完善中，欢迎指正。

**Comment by guolinke** [comment]
@bluesjjw 
感谢回复，但还是不能赞同。。（只是想纯粹的讨论）主要不理解用ps-worker的方法如何比collective communication算法更快？

map-reduce 确实是低性能，不在考虑范围。
假定用ps-worker的方式，有n个ps，n个worker ，对于每个worker，需要和n个ps都通信，每次通信的数据量为K/n (K 为总的直方图大小)。所以对单独的一个worker而言，通信次数是n，总通信量为K。这是理论的情况，实际上还要考虑多个worker同时和一个ps通信的等待问题，所以实际上还会慢点。

如果是collective communication，用state-of-the-art的reduce scatter (如recursive halving)，对于每个worker，通信次数需要的是log(n) ，总通信量是K*(n-1)(n) 。(在collective communication里面，不会出现多个worker同时互相通信然后等待的问题)。

**Comment by bluesjjw** [comment]
@guolinke 
感谢指正。
确实，PS的架构和reduce scatter在某种程度上是近似等价的（同时在一个机器上起一个worker和一个ps）。通信量也如您所算的，基本相同（K和K*(n-1)/n）。reduce scatter需要2*log(n)步通信（不能overlap），PS是bigraph的架构，需要两步通信（worker和ps的n次通信可以overlap）。所以，这两种方式应该是各有优缺点，看实际的环境。

其实，使用PS的架构，并不是说PS一定比collective communication更高效，而是因为我们的系统是一个general的系统，本身就是基于PS的架构，我们要考虑的问题是，如何在PS的架构下更高效地实现。你们的lightgbm和xgboost更专注于gbm，而我们希望能够支持更多的算法，能够实现pipeline（例如gbdt+lr）。

**Comment by guolinke** [comment]
@bluesjjw 
谢谢。我的理解是，虽然软件实现上，一台worker与不同的ps通信是可以并发（应该是你说的overlap的意思）的。但一般来说，一个机器在硬件上只有一个网卡，所以实际上的通信实际上还是串行的。

另外，reduce scatter的通信次数是log(n), 没有系数2。可以参考论文：http://wwwi10.lrr.in.tum.de/~gerndt/home/Teaching/HPCSeminar/mpich_multi_coll.pdf

**Comment by bluesjjw** [comment]
@guolinke 

单个worker与多个PS的通信是要串行，我说的overlap是指，多个worker可以同时与PS通信。

看来这篇paper大家都会看啊，我之前也看过，reduce加上broadcast还是log(n)吗？

**Comment by guolinke** [comment]
@bluesjjw 
ps也只有一个网卡，所以多个worker也不是真的可以同时与一个ps通信的。
就算假设多个worker可以同时与ps通信，对于每个worker而言，还是需要和n个ps串行的通信。所以瓶颈也还是在这里，整体来看还是需要等待n次的通信。

reduce scatter不需要broadcast的。用recursive halving算法，在log(n) 次通信后，每个worker就有可以得到部分数据的reduce结果。

**Comment by guolinke** [comment]
@andyyehoo 

> 其实，使用PS的架构，并不是说PS一定比collective communication更高效，而是因为我们的系统是一个general的系统，本身就是基于PS的架构，我们要考虑的问题是，如何在PS的架构下更高效地实现。你们的lightgbm和tianqi chen的xgboost更专注于gbm，而我们希望能够支持更多的算法，能够实现pipeline（例如gbdt+lr）。

多谢解释。我只是对GBDT文档里面写的使用ps的理由感到不解。
angel是个非常好的工作 👍  ，相信在实践场景中还是非常有用的。

**Comment by bluesjjw** [comment]
@guolinke 

每个worker是需要和n个PS通信，每次通信的数据量是K/n，合计是K，每个PS收到的数据量也是K，这应该是一个balance的网络了，应该算不上是瓶颈吧。

sorry，我表述的不够准确，我指的是broadcast reduce之后的结果，例如gbdt里面broadcast分裂结果，当然这部分开销是很小的。

**Comment by guolinke** [comment]
@bluesjjw 
从通信量来看，确实是和collective communication区别不大。并发做好的话，也能保证吞吐量，不会有空等的情况。
我主要争论的点应该是在通信次数，是需要n次的。(网卡没有并行的能力)。
这当然只是理论上的。在实际中，通信直方图的时候，由于通信量一般比较大，对于通信次数造成的延迟并不敏感。

> sorry，我表述的不够准确，我指的是broadcast reduce之后的结果，例如gbdt里面broadcast分裂结果，当然这部分开销是很小的。

Got it... 所以你才会说"两步通信”。不过我觉得这一步实际上也需要n次通信吧（每个worker接收n个ps的结果）。

**Comment by scharoun** [comment]
非常同意@guolinke的观点，angel这种做法最后会使得通信的压力全在ps上了，假设ps的数量为n, worker的数量为n, 一般情况下n>m，所以同一时刻会有多个worker向同一个ps发送直方图信息，实际上就退化成串行了，然后n个ps之间还得同步得到全局直方图信息，为了最优是不是还得使用使用类似reduce-scatter这种操作，所以通信压力均摊在每个worker上感觉是要比均摊到ps要好

**Comment by zhangyafeikimi** [comment]
楼上的太客气了, 是不是不错的工作要看有没人用, 而不是几个吹牛逼的软文.
我可以说tf是不错的工作, LightGBM是不错的工作. Angel还需要社区和时间来证明.

如上所说, Angel比较的baseline都不够高.
在PS构架上做过工作的人都知道, 网络通讯一定是瓶颈. 基于PS实现GBDT看不出必要性.

另, 性能和效果都应该和现在最先进的LightGBM比一比.

**Comment by bluesjjw** [comment]
@scharoun 

谢谢回复。

首先，我们没有说PS在所有情况下都会比collective communication更好，但是PS确实是比较适合训练高维数据的架构。在PS架构下，假设需要发送的数据是k，worker和ps都是n个（每个机器上一个worker一个ps）；一个worker需要向n-1个ps发送大小为k/n的数据，这与发一个大小为(n-1)/n*k的数据几乎没有区别（多了网络包头数据）；每个PS需要从n-1个worker接受数据，总大小是(n-1)/n*k；所以PS架构是一个很balance的网络，我不明白您说的通信压力全在PS上的意思是什么？而且，n个ps之间并不需要同步（参数被切分到n个ps上），所以也没有您说的在PS上再做reduce-scatter的必要。如果比较PS和reduce-scatter的话，通信总量一样，PS发送的数据包的数量较多，但是只需要一个step就可以得到全局直方图，reduce-scatter的通信step较多(log(n))，所以网络延迟较大或者节点数较多的情况下，reduce-scatter这部分的开销较大。

我们的论文是已经published的论文，我们投稿的时候（16年10月），lightgbm和ytk-learn都还没有开源，因此我们能比的只有MLlib和xgboost，MLlib确实是很弱，但是现在做系统的，应该都会和MLlib比一下，毕竟在工业界用的还是很多的。现在的实验，直方图设为10，但是我们的数据集维度是33W，所以一个梯度直方图的大小是50M，层数越高数据量越大，第5层就是400M了，这能算几乎没有通信量吗？不过您说的对，我们的对比实验要更多一些，后续的paper也会和lightgbm等系统对比。

BTW，我们不只是在PS上实现了一个GBDT，也对GBDT的算法做了优化，不然不会比xgboost快很多（毕竟我们的实验环境是10G的网络），会在下一篇论文中给出，也欢迎私下交流 ^_^

**Comment by guolinke** [comment]
@bluesjjw 

> 如果比较PS和reduce-scatter的话，通信总量一样，PS发送的数据包的数量较多，但是只需要一个step就可以得到全局直方图，reduce-scatter的通信step较多(log(n))，所以网络延迟较大或者节点数较多的情况下，reduce-scatter这部分的开销较大。

如之前的讨论，不同意这个观点。在网卡只有一个的时候，one-to-many的通信无论算法上怎么实现，硬件上是串行的。所以```reduce-scatter``` 的开销是更小的。
同样地，many-to-one的通信也是一样，无法实现你说的"一步"通信。

**Comment by scharoun** [comment]
@bluesjjw 
    抱歉没注意到论文的发表时间，reduce-scatter的step虽然是O(logn)，也就是建立连接的次数(延迟)为O(logn)，但是，如果在通信数据量大的情况下，数据通信时间占主导((n/(n-1))*m，m是数据量)，如果延迟时间忽略的话，那么reduce-scatter跟机器数量无关了，所以理论上是最优时间了。
    总之angel是不错的工作，好用就行! 其实gbdt训练已经很快了，从10s降到5s，表面上虽然快了一倍，但其实没啥意义~

**Comment by bluesjjw** [comment]
@scharoun 

您说的对，如果通信时间占主导，那么理论上，PS和reduce-scatter的开销基本相同。

angel刚刚开源，还要改善的地方很多，做一个好用的通用系统，工作量还是很大的。

**Comment by bluesjjw** [comment]
@guolinke 

我不太明白，您提的网卡串行的意思是什么？网卡串行对任何通信框架都是一样的，我也说了，PS把大小为k的数据分成n份来发，我并没有说这n份数据在网卡是并行传输的，我只是说，如果数据通信占主导，一次发大小为k的数据，跟发n个大小为n/k的代价基本一样（n不是非常大的情况下）。

我说的一个step指的是，一次连续的数据传输，就像ps发送n份数据，这n份数据是可以连续发出去的，中间不需要等待。而reduce-scatter每个step发完数据之后，要等待，每个节点做reduction，然后做一次同步，确定所有节点都完成了reduction，才可以开始下一个step，这一部分的开销在某些环境中是不可忽视的，更不用说在节点数不是2的倍数的时候，reduce-scatter的数据传输会增加一倍的问题（在实际环境里，节点是2的倍数的情况是少数），这是被ytk-learn证实的，这些好像您一直都没提。

回到最初的问题，不管是我们的文档，还是我的回答，从来没说过ps会在所有场景下都比collective好，我说的是，ps是一种适合高维模型的通用架构，ps和collective都有各自适合的环境，根据之前的讨论，它们都有各自的优缺点，我想这才是客观的评价吧。

**Comment by guolinke** [comment]
@bluesjjw 
谢谢解释，这次终于理解到你说的“step”的意思。抱歉，之前一直是误解的。

实际上，那个collective communication论文里面也有说到，对于reduce scatter，可以用pairwise的交换算法，通信次数会增加到n-1次，通信量不变。这样的话，也不需要等待本地的reduction结果，所以也可以认为是一个step可以完成。这个pairwise算法实际上和你们的PS架构基本是一样的。

关于2^n 的节点数，这个问题确实是有的。一般来说，会在数据包小的时候用的是recursive halving算法来降低通信次数，在数据包大的时候则用pairwise的方法来降低通信量。

总之，在ps的架构下，这样设计的并行GBDT确实是很高效了，我也没有其他的问题了。

**Comment by bluesjjw** [comment]
@guolinke 
讨论出真知嘛，也谢谢对我们提出的意见和建议。Angel还有很多工作要做。

之前读这篇paper，没太关注reduce-scatter，又读了一遍，这个方式确实是很适合GBDT的一种架构。
