### ISSUE TITLE
找不到Maven工程的pom依赖

### ISSUE THREAD

**Issue by hadp12345** [Tencent/angel#92]
提示Dependency '''com.tencent.angel:spark-on-angel-core:1.0.0''' not found，我该如何找到angel的仓库?

**Comment by paynie** [comment]
Thanks for reports this issue. At present we have not officially put Angel's jars into the public maven repositories, but it will be done sone.

**Comment by ZunwenYou** [comment]
The package have deploy to https://repo1.maven.org/maven2.

**Comment by hadp12345** [comment]
OK

**Comment by treper** [comment]
> The package have deploy to https://repo1.maven.org/maven2.

The 2.0.0-alpha version seems not deployed yet
