### ISSUE TITLE
[question]stop method of MatricesCache

### ISSUE THREAD

**Issue by pczb** [Tencent/angel#93]
the stop method of MatricesCache interrupt syncer thread if exists, however the loop catch InterruptedException which will clear the interrupt flag of syncer thread, so check `Thread.interrupted()` is alway true. (hower the stop flag is set and the syncer thread will stop).
is the thread interrupt status check for syncPolcy.sync which can be interruptted?

```java
     while (stopped.get() && !Thread.interrupted()) {
        syncPolicy.sync(PSAgentContext.get().getMatricesCache());
        try {
          Thread.sleep(syncTimeIntervalMS);
        } catch (InterruptedException e) {

        }
      }
```

**Comment by paynie** [comment]
Thanks for reports this issue. You are right, it will be fixed soon
